import { assetUrl } from "../../core/AssetUrls";

export const warshipIcon = assetUrl("images/BattleshipIconWhite.svg");
export const cityIcon = assetUrl("images/ChessKingIconWhite.svg");
export const factoryIcon = assetUrl("images/ChessQueenIconWhite.svg");
export const workshopIcon = assetUrl("images/ChessWorkshopIconWhite.svg");
export const goldCoinIcon = assetUrl("images/GoldCoinIcon.svg");
export const mirvIcon = assetUrl("images/MIRVIcon.svg");
export const missileSiloIcon = assetUrl("images/ChessKnightIconWhite.svg");
export const hydrogenBombIcon = assetUrl("images/MushroomCloudIconWhite.svg");
export const atomBombIcon = assetUrl("images/NukeIconWhite.svg");
export const portIcon = assetUrl("images/ChessRookIconWhite.svg");
export const samLauncherIcon = assetUrl("images/ChessPawnIconWhite.svg");
export const defensePostIcon = assetUrl("images/ChessBishopIconWhite.svg");
export const soldierIcon = assetUrl("images/SoldierIcon.svg");
export const claimIcon = assetUrl("images/ClaimIcon.svg");
export const profileIcon = assetUrl("images/ProfileIcon.svg");
export const guildIcon = assetUrl("images/GuildIconWhite.svg");
export const teamIcon = assetUrl("images/TeamIconSolidWhite.svg");
export const upperLimitIcon = assetUrl("images/UpperLimitIcon.svg");
export const allianceIcon = assetUrl("images/AllianceIcon.svg");
export const traitorIcon = assetUrl("images/TraitorIcon.svg");
